In [1]:
from __future__ import (absolute_import, print_function, unicode_literals,
                        division)

import logging
logging.basicConfig(level=logging.DEBUG)

import joblib
import dropbot as db
import dropbot.chip
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.ticker
import numpy as np
import pandas as pd
import si_prefix as si

# %matplotlib inline

F_formatter = mpl.ticker.FuncFormatter(lambda x, *args: si.si_format(x) + 'F')

# Open DropBot connection

In [184]:
import base_node_rpc as bnr
import base_node_rpc.proxy

try:
    proxy.terminate()
except:
    pass
proxy = db.SerialProxy(ignore=[bnr.proxy.DeviceVersionMismatch])

proxy.enable_events()

proxy.update_state(hv_output_enabled=True, hv_output_selected=True,
                   voltage=100, frequency=10e3)

# Disable channels in contact with copper tape.
# disabled_channels_mask_i = proxy.disabled_channels_mask
# disabled_channels_mask_i[[89, 30]] = 1
# proxy.disabled_channels_mask = disabled_channels_mask_i

DEBUG:base_node_rpc.async:`ProactorEventLoop` required, not `<class 'trollius.windows_events._WindowsSelectorEventLoop'>`loop in background thread.
DEBUG:base_node_rpc.async:Execute new loop in background thread.
DEBUG:trollius:Using proactor: IocpProactor
DEBUG:base_node_rpc.async:`ProactorEventLoop` required, not `<class 'trollius.windows_events._WindowsSelectorEventLoop'>`loop in background thread.
DEBUG:base_node_rpc.async:Execute new loop in background thread.
DEBUG:trollius:Using proactor: IocpProactor
DEBUG:base_node_rpc.proxy:Attempt to connect to device on port COM15 (baudrate=115200)
DEBUG:serial_device.threaded:Open `COM15` and monitor connection status
DEBUG:serial_device.threaded:connection_made: `COM15` `<ReaderThread(Thread-47, started daemon 4144)>`
DEBUG:base_node_rpc.proxy:Wait for connection to port COM15
INFO:base_node_rpc.proxy:Successfully connected to dropbot on port COM15


1

In [185]:
proxy.i2c_scan()

array([31, 32, 33, 34, 80, 81], dtype=uint8)

In [186]:
import base_node
import hv_switching_board as hv

In [172]:
# proxy.terminate()

In [187]:
CMD_GET_GENERAL_CALL_ENABLED = 0xA5
CMD_GET_SENSITIVE_CHANNELS = 0xAA
CMD_GET_SWITCHING_MATRIX_ROW = 0xA7
CMD_RAM_FREE = 0xA8
CMD_REBOOT = 0xA2
CMD_RESET_CONFIG = 0xA3
CMD_SET_GENERAL_CALL_ENABLED = 0xA4
CMD_SET_SENSITIVE_CHANNELS = 0xA9
CMD_SET_SWITCHING_MATRIX_ROW = 0xA6
PCA9505_CONFIG_IO_REGISTER_ = 0x18
PCA9505_OUTPUT_PORT_REGISTER_ = 0x08
CMD_GET_SENSITIVE_OFFSET = 0xAB


In [122]:
# hv_board_i.send_command(CMD_GET_SENSITIVE_OFFSET)
# hv_board_i.data
# proxy.i2c_read(hv_board_i.address, 5)

In [57]:
np.where(states)

(array([  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
         91,  98, 105, 112, 119]),)

In [183]:
proxy.terminate()

DEBUG:serial_device.threaded:Connection to port `COM15` closed
DEBUG:base_node_rpc.proxy:Connection lost `COM15`


In [173]:
np.packbits(states[::-1])[::-1][5:10]

array([  4,   2, 129,  64,  32], dtype=uint8)

In [189]:
states = np.zeros(proxy.number_of_channels, dtype='bool')
# states[::7] = 1
proxy.state_of_channels = states

In [190]:
hv_board_i = hv.HVSwitchingBoard(proxy, 0)

In [191]:
# hv_board_i.write_buffer = np.packbits(states)
# hv_board_i.write_buffer[:] = 0
states = np.zeros(proxy.number_of_channels, dtype='bool')
states[::7] = 1
proxy.i2c_write(0, [CMD_SET_SENSITIVE_CHANNELS] + np.packbits(states[::-1])[::-1].tolist())
# hv_board_i.send_command(CMD_SET_SENSITIVE_CHANNELS)
# proxy.i2c_read(hv_board_i.address, 5)

In [192]:
for board_id in range(3):
#     board_id = hv_board_i.address - 32
    hv_board_i = hv.HVSwitchingBoard(proxy, 32 + board_id)
    hv_board_i.send_command(CMD_GET_SENSITIVE_CHANNELS)
    print(hv_board_i.data[:5], end=', ')

    hv_board_i.send_command(CMD_GET_SENSITIVE_OFFSET)
    print(hv_board_i.data, np.packbits(states[::-1])[::-1][board_id * 5:(board_id + 1) * 5])

[129, 64, 32, 16, 8], [0, 0] [129  64  32  16   8]
[4, 2, 129, 64, 32], [6, 0] [  4   2 129  64  32]
[16, 8, 4, 2, 129], [12, 0] [ 16   8   4   2 129]


In [98]:
hv_board_i.send_command??

In [7]:

# hv_board_i.serialize_uint8(11)
# hv_board_i.send_command(CMD_SET_SWITCHING_MATRIX_ROW)

# hv_board_i.send_command(CMD_GET_GENERAL_CALL_ENABLED)
# hv_board_i.send_command(CMD_RAM_FREE)
# proxy.i2c_read(32, 1)

In [439]:
# proxy.i2c_write(0, [CMD_SET_GENERAL_CALL_ENABLED, 1])

In [204]:
proxy.state_of_channels = np.zeros(120)

proxy.i2c_write(0, [CMD_SET_SWITCHING_MATRIX_ROW, 16, states.sum()])

np.where(proxy.state_of_channels)

(array([  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
         91,  98, 105, 119]),)

In [166]:
hv_board_i.send_command(CMD_GET_SWITCHING_MATRIX_ROW)
hv_board_i.data

[5, 0]

In [364]:
proxy.i2c_write(0, [CMD_SET_SWITCHING_MATRIX_ROW])

In [334]:
proxy.i2c_send_command??

In [ ]:
broadcast.send_command

In [298]:
hv_board_i.send_command??

In [373]:
proxy.i2c_write(32, [CMD_GET_SWITCHING_MATRIX_ROW])
proxy.i2c_read_byte()

-1

In [372]:
%timeit proxy.i2c_write(32, [CMD_SET_SWITCHING_MATRIX_ROW, ])

100 loops, best of 3: 9.4 ms per loop


In [97]:
proxy.i2c_read?

In [15]:
import numpy as np

In [35]:
import base_node as bn

In [36]:
board = bn.BaseNode(proxy, address=32)

In [37]:
board.software_version()

'0.10\x00'

In [26]:
hv_board_i.analog_read(13)

ValueError: setting an array element with a sequence.

In [34]:
address = np.uint8(0x32)
n_bytes_to_read = np.uint8(3)

np.array([(address, n_bytes_to_read, )], dtype=[('address', 'uint8'), ('n_bytes_to_read', 'uint8'), ])

TypeError: data type not understood

In [7]:
proxy.i2c_request(0x32, )


In [1]:
proxy.terminate()

NameError: name 'proxy' is not defined